server:
  port: 8097  
  servlet:
    context-path: /vet
spring:
  application:
    name: vet-service
  datasource: 
    url: jdbc:postgresql://petzeydatabase.postgres.database.azure.com:5432/vetBT  
    username: postgres
    password: P@ssw0rd@123 
#    initialization-mode: always
    driver-class-name: org.postgresql.Driver    
  jpa:
    hibernate:
     ddl-auto: update    
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQL95Dialect 
        namingStrategy: org.hibernate.cfg.PhysicalNamingStrategy
        jdbc:
          lob:  
            non_contextual_creation: true  
    show-sql: true
    
  cloud:
    discovery:
      enabled: true  
         
swagger:
  url: https://vetservice.dev.skillassure.com/vet

